### PR TITLE
Compile with -Werror (treat warnings as errors)

### PR DESCRIPTION
**Pull request by lukego**
This way CI can preserve basic C coding hygiene going forwards.

### CODE REVIEW

**Comment by lukego** [comment]
I need to revisit the `nix` expression. Just now I am not actually pinning to a specific clang version and just taking the latest one available in [nixpkgs](https://github.com/nixos/nixpkgs). This makes the build dependent on the version of `nixpkgs` that you are using and that causes it to succeed on my host (running stable nixpkgs with clang 3.8) and fail on Travis-CI (running unstable nixpkgs with clang 3.9.)

I'll ask the nix people what is the best solution. The ideal would probably be to use the latest clang which would be 4.0 now. (Generally nix is very flexible and has no problem picking specific versions, adding patches, etc in a reproducible way.)

**Comment by 0xABAB** [comment]
@lukego Due to the unfortunate fact that I am banned from the NixOS organisation, I cannot give you more feedback there. 

> 
> Closing in a huff because I am annoyed by the unsolicited disparaging comments about the software that I am packaging.
> 

I am a bit surprised by this. Why are you not happy to hear new information? I am sharing the knowledge with you that the people programming Pharo don't know what they are doing and it can be be costly to depend on such software. Why don't you just *thank* me instead of becoming annoyed with what is nothing more but an accurate statement until they fix it?

Then you said the following: 
> @0xABAB Please bear with me for a bit. I am frustrated because I don't understand the process for contributing to nixpkgs (what is a "merge request"? who is "Mic92"?) and I don't enjoy the feedback you are giving me (feels a bit gratuitously negative to me and I am not sure if/how I am supposed to respond in this context i.e. on a PR that I have open.)
> 
> I am just looking for the lowest friction way to share the work that I am doing on packaging Pharo in order to avoid duplication by other people who want to use it too.

The normal process is that you do a pull request, but since you basically have to wait forever to get a PR in if you don't ask someone to merge it, the process is very much in a broken state. I told you how to play this game by requesting a merge. AFAIK, this is just English and even machines can understand that sentence. 

So, you type the at symbol (the same one which is in an e-mail address) followed by the nickname of someone who has commit access (e.g. Mic92) and then you ask if they want to merge it by saying "Can you please merge this or do you have any other concerns?". 

So, again, in my world view, I provided this "lowest friction way" to share your work using perfectly understandable English. How wrong was I to overestimate your ability to comprehend the English language. In exchange for my services (I also helped you and many others with getting their code to an acceptable level), I got banned from the NixOS organisation. 

Apparently, you are not allowed to point out obnoxious incompetent people (e.g. @Calrama) either (see: https://github.com/NixOS/nixpkgs/issues/27258), in which issue the owner of the organisation (@edolstra) claims I have done "personal attacks" before. I have only asked whether they (at that moment I referred to the entire NixOS community) are incompetent or malicious in another thread, where that statement was based on facts again (not fixing an important bug for over three years). I suggested to him that he should let other -- competent -- people manage cache.nixos.org, because he doesn't have the skills to do so. His incompetence is holding the project back.

It's just really simple. Apparently, @edolstra doesn't like it when people call him incompetent, especially if he knows it's true. So, @edolstra just waited until a situation happened where I told some other person was incompetent and as such "justified" that decision. Add to that another person who only supports him with a comment consisting of lies, because I also criticized his work the day before (he had worked on a feature for a year, but didn't complete it), and @edolstra has obtained his goal: he has managed to settle an unsettled political balance like the dictator he is. 

GitHub is just a place where dictators are born and developed.

It's just unfortunate that you too didn't have the ability to just look at the facts. In your case the facts are that Pharo has a critical bug, and the "solution" everyone seems to be happy with is one that doesn't solve anything other than providing the illusion that it works. 

I think it's just a matter of human psychology. I present the facts and an argument which nobody can counter, so instead of recognizing that the only reason for the failure of a program is their own actions it's just much easier to remove the messenger, especially if the messenger has criticism on many contributions. However, if you were to look at the facts, you would see that I did not have criticism on everything and even gave compliments in certain cases.

I find it hard to believe the entire NixOS community is full of people who believe @edolstra's bullshit.

**Comment by Laaas** [comment]
How is RaptorJIT related to NixOS?

**Comment by 0xABAB** [comment]
@Laaas It's not; it was just a communication channel I used to reply to something he asked.

**Pull request merged**
