### PR TITLE
Auditlog: Binary log of JIT and runtime behavior

### PR DESCRIPTION
**Pull request by lukego**
The new **auditlog** feature provides an "interface to external JIT analysis tools" (#22).

The auditlog is a binary file that includes all of the information necessary to support tools like `jit.v`, `jit.dump`, [LOOM](https://github.com/cloudflare/loom), and so on. The file contains very low-level data: literally memory images of individual objects in the runtime system (`GCtrace`, `GCproto`, etc.) This should be efficient in time- and space- so that it can be enabled at all times, unlike existing tracing tools. The low-level format does however require a "gdb-like" decoding step which is assumed to be handled by an external tool (out of scope for this branch.)

(Background: RaptorJIT removed the entire JIT introspection API in #36 and the auditlog is intended as a replacement that can be used in production for soft-realtime applications.)

- [x] Interface to enable and choose log filename.
- [x] [msgpack](http://msgpack.org/index.html) encoder for basic file structure.
- [x] Log trace start.
- [x] Log trace stop.
- [x] Log trace abort.
- [x] Log trace blacklisting.
- [ ] Log FFI function definitions.
- [ ] Log FFI ctype definitions.
- [ ] Log application-level machine code generation (for DynASM.)
- [ ] Log fine-grained optimizations decisions such as closure (non-)specialization (?).

### CODE REVIEW

**Comment by lukego** [comment]
Here is an example of how it works so far:

```shell
$ nix-build -A raptorjit                          # build raptorjit with nix
$ result/bin/raptorjit -e 'for i = 1, 100 do end' # one trace
$ ls -lh audit.log                                # check file size
-rw-r--r-- 1 luke users 563 May 22 10:40 audit.log
$ msgpack2json -d -c -p -i audit.log              # decode raw audit.log
{
    "type": "memory",
    "hint": "GCtrace",
    "address": 140136845447328,
    "size": 120,
    "data": <bin of size 120>
}
{
    "type": "memory",
    "hint": "MCode[]",
    "address": 709951445,
    "size": 40,
    "data": <bin of size 40>
}
{
    "type": "memory",
    "hint": "SnapShot[]",
    "address": 140136845447560,
    "size": 32,
    "data": <bin of size 32>
}
{
    "type": "memory",
    "hint": "SnapEntry[]",
    "address": 140136845447592,
    "size": 40,
    "data": <bin of size 40>
}
```

So basically the log contains a binary image of the interesting objects like the `GCtrace` and machine code and the snapshot map and so on. These memory images are tagged with their addresses so that you can follow pointers around. We need to separately build gdb-like tool(s) that decode the whole auditlog by building a partial memory image of the whole process and inspecting that. These tools could e.g. provide a compatibility layer for the LuaJIT introspection API to support offline operation of jit.v/jit.dump/LOOM/etc, or could operate on the native auditlog format (which is what I have in mind first.)

**Comment by lukego** [comment]
Started logging "events" with b302c6e. See example in commit message.

**Comment by lukego** [comment]
Pushed support for logging trace aborts.

Logs both the reason for the abort (`TraceError` code referring to [`lj_traceerr.h`](https://github.com/raptorjit/raptorjit/blob/master/src/lj_traceerr.h)) and the entire [`jit_State`](https://github.com/raptorjit/raptorjit/blob/master/src/lj_jit.h#L298-L390) record (~3KB). Could be overkill but okay for now.

Example running code that includes an NYI (call to varargs function):

```
$ raptorjit -e 'for i = 1, 100 do (function(...) return end)() end' 
$ msgpack2json -d -c -p -i audit.log
{
    "type": "memory",
    "hint": "jit_State",
    "address": 139958068037240,
    "data": <bin of size 3096>
}
{
    "type": "event",
    "event": "trace_abort",
    "jit_State": 139958068037240,
    "TraceError": 7
}
... more identical aborts ...
$ ls -lh audit.log 
-rw-r--r-- 1 luke users 13K May 24 08:16 audit.log
```

Certain trace aborts have additional information in `jit_State->errinfo` which is a tagged Lua object (`TValue`). Currently we only have a shallow copy of `TValue errinfo` in the `jit_State` memory and that is probably not sufficient e.g. if the error is a string with contents elsewhere in memory. Could perhaps either "deeply" log that object (i.e. also log the referenced memory) or alternatively decode it during logging and put the contents into the msgpack event.

**Comment by lukego** [comment]
So! This branch already supports dumping some JIT internal data structures like `GCtrace`. The next step is for external tools to be able to interpret them.

I have taken the next two baby steps actually:

RaptorJIT build now includes a `raptorjit.dwo` file that contains DWARF debug information for all internal data structures (#64).

[Studio](https://github.com/studio/studio) now includes a tool called Dwarfish (https://github.com/studio/studio/pull/14) that converts from the binary DWARF format into easier to parse YAML and JSON descriptions like this:

```
<28b8>:                                                                                                                                                                                                             
  tag: structure_type
  name: GCtrace
  byte_size: 120
  decl_file: 27
  decl_line: 176
  sibling: <0x29e7>
<28c2>:
  tag: member
  name: nextgc
  decl_file: 27
  decl_line: 177
  type: <0xefe>
  data_member_location: 0
<28cc>:
  tag: member
  name: marked
  decl_file: 27
  decl_line: 177
  type: <0x5aa>
  data_member_location: 8
```

This describes the whole layout of all the internal RaptorJIT data structures including the symbolic constants like IR instruction enums, etc.

The next big milestone for me will be to extend the graphical [GT Inspector](http://gtoolkit.org/#playinspector) to explore the audit log in its native format e.g. so that you can click on a trace and see the IR listing, etc.

**Comment by wingo** [comment]
You might consider https://wingolog.org/archives/2012/06/19/dltool-mines-dwarf at some point.  Dunno, just leaving this here :)

**Comment by lukego** [comment]
@wingo Oh hey that looks really nice :). I think it would have been a nice solution and the Guile dependency would be no problem with Nix. Too late for current purposes though: I have decoded the DWARF type information in Pharo (via the YAML/JSON pipeline) and now I am on to using it to decode the heap data.

**Comment by lukego** [comment]
So!

I have built a low-level (gdb-style) debugger now. This takes two inputs: the `audit.log` in msgpack format and the C type information in DWARF format. The log is decoded and explored using the type information. This lets you see what decisions the JIT made during execution by examining snapshots of its own internal data structures like `jit_State`, `GCtrace`, etc.

Screenshot:

pharoscreenshot 1

The next step is to build a high-level (LOOM-style) debugger on top. This will take the low-level C structures like `GCtrace` and present them in user-friendly ways e.g. IR listings, mcode disassembly, reasons for trace aborts, etc. Then we will have a convenient high-level way to review the JIT behavior for processes either while they are running or after they have terminated.

Then after that it will be time to build some really interesting features new...

**Comment by lukego** [comment]
I am experimenting with some [Roassal](http://agilevisualization.com/) visualizations of trace data now. It's quite fun :).

First up is an alternative to `jit.v` i.e. a high-level overview of the code that has been generated. Here we just want to see an overview of what traces we have, what is their shape (how many loop and non-loop instructions), what is their theme (e.g. mostly arithmetic? how much type conversions? any unsunk allocations? any FFI calls? etc.) I think a separate visualization is needed for the `jit.dump` scenario where we really want to understand one trace in detail.

The visualization is big. The idea is to browse it with zoom. I didn't quite manage to export it as SVG this time so I'll just make a couple of PNG screenshots at interesting zoom levels. This is based on the auditlog from running the standard benchmark `scimark ffi`.

Overview of traces with side-trace linkage:

screen shot 2017-06-17 at 15 45 05

Zooming in on the trace at the top:

screen shot 2017-06-17 at 15 48 24

Legend:

The outer boxes (light gray) are traces. The inner boxes (dark gray) are sets of IR instructions: one for the head of the trace on the left and then one for the loop of the trace (if present) on the right. So you can easily see whether the trace has a loop and the amount of work it does inside and outside that loop.

The colored boxes as individual IR instructions. The colors are simple categorizations: green for arithmetic, orange for FFI, peach for guards and type conversions, blue for memory access, and red for allocation. The idea - untested - is to give a relevant impression of a trace: an unsunk allocation will jump out in bright red, the ratio of arithmetic to memory access to type conversions should be apparent, etc.

More experiments to follow :-)

**Comment by lukego** [comment]
Please excuse me going all stream of consciousness here with rough drafts :).

Here is an experiment to layout the IR instructions in a tree with edges showing the SSA references to the values of previous instructions.

screen shot 2017-06-18 at 06 10 23

The basic idea here is to illustrate the _dependency chains_ between instructions and give a feeling for how well a superscalar CPU will be able execute instructions in parallel. Loosely speaking, the _height_ of the trace is suggestive of its overall latency - and execution time - while the widget suggests how many instructions the processor will be executing in parallel.

Here is a close up on a small trace that contains a loop:

screen shot 2017-06-18 at 06 20 57

**Comment by lukego** [comment]
See related discussion over at https://github.com/LuaJIT/LuaJIT/issues/248#issuecomment-274029158 where the number of instructions in LuaJIT-generated code did not predict its performance nearly so well as looking at the dependencies between instructions. Have to see if this analysis generalizes well to other code and from mcode to IR. I am hopeful.

also in hardcore optimization books like [CSAPP:3](https://www.amazon.com/Computer-Systems-Programmers-Perspective-3rd/dp/013409266X) the mental model for thinking about performance on modern CPUs is mostly to identify the longest dependency chain (and to account for how dependencies are carried from one iteration of a loop to the next.) This seems to me quite amenable to automation especially in code from a tracing JIT where the branches are all statically predicts (i.e. they are for guards and will not be taken on the fast path.)

**Comment by eugeneia** [comment]
Wow this looks great! I really like the color coding and depth/width approximation as a high level glance at low level stuff!

**Comment by raj2569** [comment]
Looks neat... Is this in a position to be tried out ?

**Comment by lukego** [comment]
I have a first cut at integrating profiler data now.

This is really critical to solve the "needle in a haystack" problem. Real applications like Snabb will have hundreds of traces but only a small subset will be relevant to performance and worth inspecting. The tooling needs to help us to focus our attention on the traces that actually matter so that we don't waste time looking at code that is not worth optimizing.

Here is a simple before-and-after example: first the complete trace set and then enhanced with profiler data. This is from the same small (~50 line) program from before. It's the LuaJIT "scimark-fft" benchmark and it generated 21 traces.

Here is the full "haystack" including all traces. (It's bigger than the screenshots earlier because I had quietly cropped them a bit to make them less unmanageable.)

screen shot 2017-06-19 at 13 03 48

Here is the profiled-driven view of the "needles" in that haystack. Traces using <5% CPU were removed and the "redness" of the remaining code indicates how much time it consumed:

screen shot 2017-06-19 at 12 43 51

This really cuts down the distractions!

Observations:

- Trace 16 is the hottest important by far.
- The "head" and "loop" of trace 16 were equally hot. This suggests that it is branchy. Instead of spinning around inside the loop it is often re-entering the head. This is presumably happening due to some guard assertions (peach colored boxes) failing and forcing exits to side-traces (likely traces 17 and 18 that we see connected.)
- Traces 8 and 15 are also warm. Trace 8 spends more time in the head while Trace 15 spends more time in its loop.

I suppose the next big question is: How do these traces relate to the source code? Then maybe we can understand what is going on and whether we could make improvements e.g. to reformulate the code so that Trace 16 doesn't exit the loop so frequently.

**Comment by lukego** [comment]
Hey allow me to digress and use Trace 16 to illustrate what the whole "head" vs "loop" distinction is about.

If you have a loop in your code like this:

```
while condition do
   ...body...
end
```

Then the JIT will actually generate two different versions of the `...body...` code in the loop:

- The `head` code is for the first iteration of the loop. Here we are in a blank state: we don't have any values stored in CPU registers yet. For each value that we want to access, like a local variable or a table member etc, we need to load it into a register and check that it has the right type. This code is expected to have a fair number of load instructions (light blue) and type assertion/conversion instructions (peach.)
- The `loop` code is specifically for the subsequent loop iterations. Here we are executing the same source code as in the `head` trace - it's still the same Lua code - but in the generated code we can reuse any state that we already have in registers from the previous iteration. So if the `head` code has already loaded values and checked their values then we can skip those instructions in the `loop` part and simply reuse the results.

So this is basically what we can see in Trace 16. The `head` has more blue and peach instructions along the top where values are loaded and validated with things like array bounds checks. These instructions have disappeared in the `loop` trace and what remains is mostly the chain of arithmetic (green) leading to stores of results (dark blue) down towards the bottom.

Here's a more zoomed in view:

screen shot 2017-06-19 at 20 11 39

So we can see visually how the JIT "loop optimization" works. Cool, huh?

In this instance it has eliminated a lot of instructions _but_ the height of the boxes is still similar so it is conceivable to me that this does not have a large impact on actual execution time. I would expect more benefit in cases where the eliminated instructions shorten the tree instead of trimming short branches near the top. However more experience is needed to know whether "minimize the number of instructions" or "minimize the height of the box" will be the most useful optimization goal.

There is also a significant detail that I need to add to this visualization: whether each instruction is storing a value in a register (cheap) or on the stack (more expensive.) If we are juggling too many values then we won't fit them all in registers and some will need to go on the stack. If we have too much stack manipulation on our long chains of instructions then this can increase the time it takes to complete an iteration.

**Comment by lukego** [comment]
@raj2569 Not ready to play with yet. Haven't even checked it into Git yet. But - nearly at the point where it is time to start thinking about how to package it up and share it.

**Comment by lukego** [comment]
Just one more digression :-)

This also illustrates why the JIT is so well adapted to an out-of-order/superscalar CPU like recent Intel ones. The machine code contains a lot of instructions but many of them can be executed in parallel. Checking the types of parameters will not really slow things down - won't increase the height of the box - because it can be taken on the side while the CPU is also performing the chain of arithmetic.

If we were working with simpler CPUs based on in-order execution, where you execute instructions one by one and have to pay for all of them, then I think these instructions would become cripplingly expensive and we would be better off with another programming language that eliminates the checks at compile-time (e.g. C or Rust or ...). Computer architecture matters!

**Comment by javierguerragiraldez** [comment]
nitpickings on the loop optimization:

- the header isn't always the first iteration.  in fact, it's usually the 57'th one (after the loop was detected as hot and traced/compiled)  also, any side trace that returns to the loop enters again at the top, so the head executes again.  that's what makes loops with common sidetraces slower, as it negates the loop optimization.

- the loop part isn't generated from Lua, it's just a literal copy of the head, with all the loop-invariant code removed and some phi-reassignment.

it helps to remember that the traces are linear code snippets, there are no conditionals apart from the guards (that can only exit the trace), and no jump to the middle of a trace, neither from another trace nor from within itself. every trace always starts at the top.

this also has an initially puzzling consequence in the tracing code: if the JIT finds a loop while recording a trace, it will abort the current trace (but not penalize it) and (probably) start a new one, to prioritize traces that exactly match the looping code.  if successful, the loop trace always ends with a jump to the very beginning, the simplest kind of loop.  it's only after that that the loop optimization kicks in, unrolling it once and trimming the copy.  Still, a loop trace is always the same as if jumping to the top.

**Comment by lukego** [comment]
> if the JIT finds a loop while recording a trace, it will abort the current trace (but not penalize it) and (probably) start a new one, to prioritize traces that exactly match the looping code

I didn't know that. So if you have code like this:

```
...outside...
while condition do
   ...inside...
end
```

Then the `...outside...` code will be compiled separately? I had been thinking that it could be included in the head of the loop trace. On reflection though my original interpretation does not make sense: if you branch to the head of the loop trace then you expect to execute one iteration of the loop, but if you included the `...outside...` code in the head then you would be re-running that too.

> the header isn't always the first iteration. in fact, it's usually the 57'th one

I suspect that we have the same mental model here but that it is hard to talk about without really having an established vocabulary. Perhaps we need a "tracing JIT glossary"?

On the one hand the trace will be _recorded and compiled_ on the 57th or so iteration of the loop i.e. when the code is judged to have become "hot." During this iteration the JIT will observe the types of all arguments, whether each `if` statement takes the `then` or `else` branch, etc, and it will generate code that depends on exactly those same types and branch choices.

On the other hand the `head` of the trace will be _executed_ on the first iteration when entering the loop after it has been compiled, and again after any subsequent iterations of the loop that take a side-exit from the optimized `loop` version of the trace. Sides exits are taken when any one of the guarded assertions (peach colored instructions) is not satisfied (e.g. an argument does not have the same type that it did during recording, an `if` does not take the same branch that it did during recording, an array bounds check fails, etc.)

Right?

Great to be able to talk with you about this stuff @javierguerragiraldez!

**Comment by lukego** [comment]
Oh hey I said this about the loop optimization in this example:

> In this instance it has eliminated a lot of instructions but the height of the boxes is still similar so it is conceivable to me that this does not have a large impact on actual execution time.

Turns out that I have data from a [previous benchmark](https://github.com/raptorjit/raptorjit/issues/46#issuecomment-288061478) to test this hypothesis with. That benchmark includes a comparison with default settings (red) vs with loop optimization completely disabled (green). On this benchmark (`scimark-fft`) we see only 0.65x normal performance when loop optimization is disabled. So the optimization is helping substantially despite only modestly reducing the height of the box in the visualization.

@javierguerragiraldez Is it also the case that without loop optimization you need to restore a snapshot (flush all registers to the Lua stack) on each iteration? That seems potentially expensive too. I wonder if VMProfile ought to be able to pick that up i.e. detect how much time is spent restoring snapshots...

**Comment by lukego** [comment]
Just looking ahead into the rosy future...

The next big step would be to create a lower-level instruction-flow-visualization based on the machine code rather than the IR code. Here we would take care of vertical space to show the latency of each individual instruction e.g. that you need to wait 1 cycle for an integer addition, 3 cycles for an integer multiplication, 4 cycles for a memory load assuming it comes from L1 cache on a Haswell CPU, etc.

Once we do this then we should have an extremely accurate performance analyzer that could be used for traces and also for e.g. assembler code that we write with DynASM. However - I think we will get a lot of value out of the IR-level view in the meantime.

Related Intel tool: https://software.intel.com/en-us/articles/intel-architecture-code-analyzer

**Comment by javierguerragiraldez** [comment]
> Then the ...outside... code will be compiled separately?

yes, check `rec_loop_interp()` https://github.com/raptorjit/raptorjit/blob/master/src/lj_record.c#L538-L566

words are hard!  but yes, i think your description is right.  the important thing is that a trace is just a simple block of code; with multiple exits but a single entry (at the top)  the fact that a loop hooks at midpoint is an implementation detail.  any reenter to that trace (either a new loop or a return from a sidetrace) is always from the top and executes the header once.

i don't think a non-loop-optimized loop reloads its snapshot on every iteration, i don't have them in front of me, but i remember a simple jump to the top.  also, the loop-optimized code (which does end in a simple jump to the midpoint) must be exactly equivalent, and any exit must get to the same state either optimized or not; so i guess the snapshot use should be equivalent.

I still have a hard time finding the relation between the mcode and IR....

**Comment by lukego** [comment]
> I still have a hard time finding the relation between the mcode and IR....

I am not actively working on this but I do want it and I see a couple of possible approaches.

First would be for the code generator to create a precise mapping. I'm not sure how hard that would be. Downside is that this adds code to the JIT which is already too complex. But maybe fine if the added complexity is low.

Second would be to use some heuristic matching algorithm, e.g. based on `diff` or [parsing with bounded seas](http://scg.unibe.ch/archive/papers/Kurs14b-BoundedSeas.pdf), to detect the features in the IR and mcode that are expected to match. If we assume that the IR and mcode instruction sequences are more-or-less in the same order, that register assignments in the IR code will usually also appear in the generated mcode, that guards will usually include a conditional branch instructions, etc, then it seems likely we could find a high-quality approximate mapping.

**Comment by lukego** [comment]
Here is a revision with some visual tweaking (click to zoom):

screen shot 2017-06-21 at 18 34 47

The labels are legible now.

The edges also follow a strict invariant: connect from the bottom-center of the source to either the left-corner (for operand 1) or right-corner (for operand 2).

One missing invariant is for dependency edges to always point upwards. There is a `sub` here that references a `mul` but appears on the same vertical position.

Some important missing details are references to constants or values reused from the trace head...

**Comment by lukego** [comment]
Let me take this diagram to highlight something really cool about modern Intel CPUs.

Consider these three instructions:

screen shot 2017-06-21 at 18 57 28

Here we use arithmetic to update an array index (`add`) and use that both for an array bounds check (`abc`) and an array pointer dereference (`aref`). The curious thing is that the bounds check and the pointer dereference are shown side-by-side suggesting that they can operate in parallel. How can this be? Don't you have to do the bounds check first before you can dereference the pointer?

The answer is no. If the CPU supports [out-of-order execution](https://en.wikipedia.org/wiki/Out-of-order_execution) then it can execute both instructions simultaneously, in the same cycle. The catch is that it has to commit the results ("retire the instructions") in strict sequential order. So it's a bit like a database: each instruction runs in a transaction and if the `abc` bounds check transaction fails then the `aref` lookup has to be rolled back (which suppresses any side-effects it might have had like raising a segfault exception.)

Here is what actually happens:

1. The CPU sees the instructions for the bounds check: load the size, compare with the index, conditionally branch to an error handler if out of bounds.
2. The CPU starts executing these instructions. This could potentially take a while: the load could take anything from 4 cycles (L1 cache) to hundreds of cycles (RAM.) 
3. The CPU _predicts_ that the array bounds check will succeed and that the branch to an error handler will not be taken. This prediction suggrests that the next instructions to run will be the array pointer dereference (not the error handler.)
4. The CPU executes the array dereference and keeps its result (write value to register or raise segfault) in internal temporary storage pending the result of the bounds check.
5. The bounds check instructions complete and are _retired_. If the bounds check succeeded then the prediction has come true and the array dereference instructions can also be retired. On the other hand if the bounds check failed then we have _mispredicted_ and the conditional branch to the error handler should have been taken. In this case the CPU simply discards the preliminary results from the array dereference and starts over on the instructions that it really should be executing.

Cool, huh?

This is actually similar to the way Lisp Machines worked, as I understand it. They would have an `ADD` instruction that can detect whether the arguments are fixnums, bignums, or something invalid, and to do the right thing. This logic can all run in the same cycle because it is _microcoded_ i.e. implemented deep inside the CPU. On modern out-of-order CPUs we don't need microcode for this anymore because the automatic dependency analysis and transaction semantics solve the problem for normal instructions.

Great work, CPU hackers!

**Comment by lukego** [comment]
Here is the source code that should correspond with this IR btw:

```
      for i=a,a+2*(n-dual2),2*dual2 do
	local j = i+dual2
	local jr, ji = v[j], v[j+1]
	local dr, di = wr*jr - wi*ji, wr*ji + wi*jr
	local ir, ii = v[i], v[i+1]
	v[j], v[j+1] = ir - dr, ii - di
	v[i], v[i+1] = ir + dr, ii + di
      end
```

See the same structure: Load four values from arrays, perform arithmetic on them, store four results back in the arrays (at the same locations: reused `aref` nodes).

The loop iteration is done by the top-rightmost IR code: bump the loop counter with `add`, test for termination with an `le` (less than) guarded assertion (trace exists if limit reached), and forward the updated loop index into the next iteration (that is what `phi` does.)

**Comment by lukego** [comment]
Just another little screenshot. I have cooked up a GUI where you can enter some code on the left and immediately see the JIT visualization on the right. The code is specified as a Nix expression and that is quite flexible: can write the Lua code inline, or fetch it from a gist, or skip the source and inspect a trace tarball from the CI server, etc.

screen shot 2017-07-26 at 14 26 27

Plan is to polish it up a little more (e.g. hook in the profiler highlighting) and then make it easy to run for everybody here.

The deployment model that I have in mind for this GUI is that it runs on a server somewhere and you access it with a VNC viewer. Can also run it on any Linux box though.

**Comment by lukego** [comment]
Here is another screen shot that starts to tie the components together. It's wide - click to zoom.

screen shot 2017-08-02 at 13 42 44

The flow is from left to right:

- The first panel is a list of VMProfile data sets. This data comes from a [test application](https://github.com/lukego/rj-vmprof-bench/) that runs several of the standard LuaJIT benchmarks in the same VM and switches to a new VMProfile for each one so that the results can be viewed separately.
- The second panel is a graph of "hot traces" for the selected profile. This shows set of traces (root trace + all children) that account for at least 1% CPU for the selected profile. The traces are shaded red according to their "hotness."
- The third panel is a graph of the IR instructions in the selected (by mouse click) hot trace. This just is a visual IR instruction listing.

There is a _lot_ more to add but this is approaching something usable now.

**Comment by eugeneia** [comment]
Can’t wait to play with this!

**Comment by lukego** [comment]
Just a minor tooling milestone: I implemented an [IR Listing](https://hydra.snabb.co/build/2037769/download/1/studio.html#view-ir-listing) tab in the Studio UI. This is basically reconstructing the LuaJIT `-jdump=i` using the audit log. So - with the right analysis tool it is now possible to get IR dumps from RaptorJIT.

**Comment by lukego** [comment]
Latest screenshot of how the tooling is shaping up:

insp

and mouseover help:

screenshot 2017-09-07 16 38 41

**Comment by lukego** [comment]
Here is another screenshot of the tooling. I am setting up an end-to-end profiling workflow that starts with picking a profile, then picking a line of code that got hot, then picking a root/side trace that was spawned from that point, then looking at the IR code, etc. Click to zoom.

screen shot 2017-11-24 at 14 40 32

**Comment by lukego** [comment]
This stuff is really coming together!!!

I'm quite at the moment because I am working like crazy on the UI for visualizing JIT data and keeping up with the demands of the early users in the Snabb universe. This is all coming upstream to this RaptorJIT repo really soon though.

Here's a screenshot of disassembling IR instructions with a mouseover tooltip:

screenshot 2018-04-25 21 29 01 2

**Comment by lukego** [comment]
w00t!

This branch took more than a year to bake to maturity in parallel with the graphical analysis tools. Landed now 😁

**Pull request merged**
