### PR TITLE
The Great #define Purge

### PR DESCRIPTION
**Pull request by ZirconiumX**
This is a little more modest than my last patch, but still removes more code.

I plan to also force-on `LJ_FR2` and `LJ_64`.

### CODE REVIEW

**Comment by ZirconiumX** [comment]
Note for other people, to re-bootstrap the VM, do
```sh
cd src/reusevm
find . -type f -exec cp ../{} {} \;
```
And then check-in the new files.

**Comment by lukego** [comment]
Great stuff!

I have read through the whole diff as a second pair of eyes and I didn't find any problems. There were a few places I needed to look at carefully and so I think that I successfully kept my brain engaged from start to end :)

**Comment by lukego** [comment]
Incidentally I think these changes make the code much more readable! It's tricky having all those build options so intricately woven throughout the compiler and runtime system.

**Comment by ZirconiumX** [comment]
I'll admit, I'm not entirely happy with some of them, but we can always
tidy up the code later, or rewrite it.

**Pull request merged**
